# -*- coding: utf-8 -*-
"""basicPandas(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B70q4Jk9rYox1T_0L2ukP_rKM7oBjplQ
"""

import pandas as pd
import numpy as np

####SELECTION & DROP ####

df = pd.read_csv("sample_data/california_housing_test.csv")



from pandas import Series
s1 = Series(
    range(1,6), index=(list("abcde"))
)

#### MAP & LAMDA & APPLY ####

s1 = Series(np.arange(10))

s1.head(5)

s1.map(lambda x: x**2).head(5)

#dict type에도 적용이 가능

z = {1: "A",2:"B",3:"C"}

s1.map(z).head(5)

s2 = Series(np.arange(10,20))
s1.map(s2).head(5)

#### APPLY ####