# -*- coding: utf-8 -*-
"""basicPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTkzsPVTm8CSoUpdIylf75MXpMZsjIGa
"""

import pandas as pd


#판다스로 기본적인 데이터 테이블 불러오기

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'

df_data = pd.read_csv(data_url, sep='\s+', header =None)

#sample의 첫 5줄을 출력
df_data.head()

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

#기본적인 Series 사용법

list_data = [1,2,3,4,5]

example_obj = Series(data=list_data)
example_obj

#Series의 Index값을 지정해 줄 수 있다.

list_name = ['a', 'b','c','d','e']
example_obj = Series(data=list_data, index=list_name)

example_obj

#data index로 접근하기

example_obj['a']

#할당도 가능
example_obj['a'] = 2

#data type도 변환 가능

example_obj = example_obj.astype(float)

example_obj['a'] = 3.2
example_obj

#Series/Index의 이름도 지정해 줄 수 있다

example_obj.name = "number"
example_obj.index.name = "char"

example_obj

#Series 생성시 Index기준으로 생성이됨. 
#인덱스가 데이터보다 많다면 그 자리는 Nan으로 반환

dict_data = {'a':1, 'b':2,'c':3,'d':4,'e':5}

indices = ['a','b','c','d','e','f','g','h']

series_obj_1 = Series(dict_data, index = indices)
series_obj_1

####DATAFRAME#####

#Dataframe은 간단하게 series들의 모임

#하나의 데이터에 접근하기 위해선 idx,col 다 알아야함

#보통은 csv,excel파일을 불러와서 활용을 하나, 지금은 연습용!

raw_data = {
    "first_name":["J","M","T","JJ","A"],
    "last_name":["M","F","E","E","C"],
    "age":[4,32,22,53,13],
    "city":["S","B","M","D","B"]
}

df = pd.DataFrame(raw_data, columns =["first_name","last_name","age","city"])
df

#데이터들중 원하는 시리즈만으로 프레임을 만들 수 있다.
DataFrame(raw_data, columns=["age","city"])

#없는 index를 넣으면 빈 공간으로 생성을 한다

DataFrame(raw_data, columns=["first_name","debt"])

#데이터를 추출할때 property방식으로도 가능하고, dict형식으로 불러 올 수도 있다.

df.first_name
df["first_name"]

#Indexing

#loc: index location
#index가 꼭 1번부터 시작하진 않으니까

df.loc[:3]

#iloc: index position

df.age.iloc[:3]

